runtime: python37

#env_variables:
#  MYSQL_DSN: $MYSQL_DSN
#  MYSQL_USER: $MYSQL_USER
#  MYSQL_PASSWORD: $MYSQL_PASSWORD

entrypoint: gunicorn -b :5000 runserver:app

runtime_config:
    python_version: 3